### ISSUE TITLE
Create Window Movement and Opening/Closing Commands

### ISSUE THREAD

**Issue by apiedev** [UW-UPL/UPL-MMORPG#16]
In-game windows have been made, however, they need to now be clicked on and moved without moving the actual game. 
- Make function in each Window that can return if its hovered or not.
- Make iterator that will call to these functions before Panel movement happens.

**Comment by jdetter** [comment]
@pierrce do you have a separate branch for the progress on this?

**Comment by apiedev** [comment]
Oh, hey John, just cleaning out my issues.

**Comment by jdetter** [comment]
I forgot this project even existed lmao
![wtf](https://user-images.githubusercontent.com/4099508/111862860-058fba00-8926-11eb-9476-e3f82ee8f075.gif)
