### ISSUE TITLE
Create startup screen

### ISSUE THREAD

**Issue by jdetter** [UW-UPL/UPL-MMORPG#7]
The game takes a couple of seconds to load so it would be cool to have like a loading screen and progress bar.

**Comment by LOZORD** [comment]
You should use assets from the [Media repo](https://github.com/UW-UPL/Media) if possible.

**Comment by jdetter** [comment]
@LOZORD good idea! =D

**Comment by apiedev** [comment]
There will need to be one soon anyways for Logging in correct?

**Comment by jdetter** [comment]
Yup! I'll be working on the networking stuff tonight so I will probably do this tonight.

**Comment by jdetter** [comment]
This is complete for now -- will revisit when we want a better login/startup screen.
